const express=require("express")
const useRouter=express.Router()
const path=require("path")
const rootDir=require("../utils/utilPath")
const { registeredHome } = require("../controllers/hostcontroller")
const storeController=require("../controllers/storecontroller")
useRouter.get("/",storeController.getIndex)
useRouter.get("/Homes",storeController.getHomeList)
useRouter.get("/bookings",storeController.getBookings)
useRouter.get("/favourite",storeController.getFavouriteList)
module.exports=useRouter